export const GAMES = [
  {
    href: '/games/color-match',
    name: 'Color Match',
    description: 'Tap matching tiles. 60 seconds.',
    emoji: '🎨',
    bg: '#3B82F6',
  },
  {
    href: '/games/memory-flip',
    name: 'Memory Flip',
    description: 'Find matching pairs. Beat the clock.',
    emoji: '🃏',
    bg: '#8B5CF6',
  },
  {
    href: '/games/number-rush',
    name: 'Number Rush',
    description: 'Tap 1→25 in order. How fast are you?',
    emoji: '⚡',
    bg: '#10B981',
  },
  {
    href: '/games/pattern-echo',
    name: 'Pattern Echo',
    description: 'Watch the sequence. Repeat it.',
    emoji: '🔮',
    bg: '#F59E0B',
  },
  {
    href: '/games/word-scramble',
    name: 'Word Scramble',
    description: 'Unscramble words. 60 seconds.',
    emoji: '🔤',
    bg: '#EC4899',
  },
  {
    href: '/games/typing-speed',
    name: 'Typing Speed',
    description: 'Type a passage. How fast are you?',
    emoji: '⌨️',
    bg: '#06B6D4',
  },
  {
    href: '/games/reaction-time',
    name: 'Reaction Time',
    description: 'Tap when it turns green. 5 rounds.',
    emoji: '⚡',
    bg: '#22C55E',
  },
  {
    href: '/games/snake',
    name: 'Snake',
    description: 'Eat food. Grow longer. Classic.',
    emoji: '🐍',
    bg: '#16A34A',
  },
  {
    href: '/games/2048',
    name: '2048',
    description: 'Slide tiles. Merge numbers. Reach 2048.',
    emoji: '🎯',
    bg: '#F59E0B',
  },
  {
    href: '/games/whack-a-mole',
    name: 'Whack-a-Mole',
    description: 'Tap moles as they pop up. 30 seconds.',
    emoji: '🔨',
    bg: '#92400E',
  },
  {
    href: '/games/tic-tac-toe',
    name: 'Tic-Tac-Toe',
    description: 'Classic 3×3. Beat the AI.',
    emoji: '⭕',
    bg: '#6366F1',
  },
  {
    href: '/games/sudoku',
    name: 'Sudoku',
    description: 'Fill the grid. No repeats.',
    emoji: '🔢',
    bg: '#0EA5E9',
  },
  {
    href: '/games/minesweeper',
    name: 'Minesweeper',
    description: 'Find all safe squares. No booms.',
    emoji: '💣',
    bg: '#64748B',
  },
] as const;

export type Game = (typeof GAMES)[number];
